//! Embeds the campaign mission files for targets without a filesystem — the WASM / itch.io
//! browser build (owner ask, 2026-07-08): scans `../../assets/levels` and generates
//! `embedded_levels.rs` in OUT_DIR, a static `(relative path, contents)` table of
//! `include_str!` entries. Native builds keep reading the real files at runtime (the
//! edit-without-recompile workflow is untouched); the table is only *referenced* under
//! `cfg(target_arch = "wasm32")` — but it is generated for every target, so a level edit
//! does retrigger this script (cheap: it only writes a table of paths).

use std::fmt::Write as _;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this");
    let root = std::path::Path::new(&manifest).join("../../assets/levels");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut files: Vec<(String, std::path::PathBuf)> = Vec::new();
    if let Ok(rd) = std::fs::read_dir(&root) {
        let mut top: Vec<_> = rd.filter_map(|e| e.ok().map(|e| e.path())).collect();
        top.sort();
        for entry in top {
            if entry.is_dir() {
                let dir_name = entry.file_name().unwrap_or_default().to_string_lossy().into_owned();
                let mut inner: Vec<_> = std::fs::read_dir(&entry)
                    .into_iter()
                    .flatten()
                    .filter_map(|e| e.ok().map(|e| e.path()))
                    .collect();
                inner.sort();
                for f in inner.into_iter().filter(|f| f.is_file()) {
                    let name = f.file_name().unwrap_or_default().to_string_lossy().into_owned();
                    files.push((format!("{dir_name}/{name}"), f));
                }
            } else if entry.is_file() {
                let name = entry.file_name().unwrap_or_default().to_string_lossy().into_owned();
                files.push((name, entry));
            }
        }
    }

    let mut out = String::from(
        "/// (path relative to assets/levels, contents) — generated by levels/build.rs.\n\
         #[allow(dead_code)]\n\
         pub static EMBEDDED_LEVELS: &[(&str, &str)] = &[\n",
    );
    for (rel, path) in &files {
        // include_str! rejects extended-length (\\?\) paths; keep the plain absolute form.
        let abs = path
            .canonicalize()
            .unwrap_or_else(|_| path.clone())
            .to_string_lossy()
            .trim_start_matches(r"\\?\")
            .to_string();
        let _ = writeln!(out, "    ({rel:?}, include_str!({abs:?})),");
    }
    out.push_str("];\n");
    let dest = std::path::Path::new(&std::env::var("OUT_DIR").expect("cargo sets this"))
        .join("embedded_levels.rs");
    std::fs::write(dest, out).expect("write embedded_levels.rs");
}
