//! Embeds the campaign mission files for targets without a filesystem — the WASM / itch.io
//! browser build (owner ask, 2026-07-08): scans `../../assets/levels` and generates
//! `embedded_levels.rs` in OUT_DIR, a static `(relative path, contents)` table of
//! `include_str!` entries.
//!
//! WASM-ONLY, both the table and the rerun trigger (owner fix, 2026-07-19): the table used
//! to be generated — with its `include_str!` entries — for every target, which silently
//! made each `.lvl` a rustc input of this crate on NATIVE too, so a level tweak cost a
//! `levels`+`game` rebuild. That defeats the entire point of data-driven levels (native
//! reads the real files at runtime; see `campaign::assets_dir`). Now native gets an EMPTY
//! table and no asset watch: editing a mission file touches nothing the native build
//! tracks. The wasm target keeps the watch, so packaging the browser build re-embeds
//! fresh levels as before.

use std::fmt::Write as _;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let dest = std::path::Path::new(&std::env::var("OUT_DIR").expect("cargo sets this"))
        .join("embedded_levels.rs");

    let target = std::env::var("TARGET").unwrap_or_default();
    if !target.starts_with("wasm32") {
        // NATIVE: levels load from disk at runtime — the mission files must not be
        // compile inputs in any form (no include_str!, no rerun-if-changed).
        std::fs::write(
            &dest,
            "/// Empty on native targets — levels load from disk at runtime (see build.rs).\n\
             #[allow(dead_code)]\n\
             pub static EMBEDDED_LEVELS: &[(&str, &str)] = &[];\n",
        )
        .expect("write embedded_levels.rs");
        return;
    }

    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this");
    let root = std::path::Path::new(&manifest).join("../../assets/levels");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut files: Vec<(String, std::path::PathBuf)> = Vec::new();
    // Recursively collect every file under assets/levels — missions may be nested in per-arc
    // folders. Paths are recorded RELATIVE to the root, `/`-separated, so the wasm loader resolves
    // `.brf` companions from a `.lvl`'s stem regardless of nesting depth.
    fn walk(dir: &std::path::Path, root: &std::path::Path, out: &mut Vec<(String, std::path::PathBuf)>) {
        let Ok(rd) = std::fs::read_dir(dir) else { return };
        let mut entries: Vec<_> = rd.filter_map(|e| e.ok().map(|e| e.path())).collect();
        entries.sort();
        for p in entries {
            if p.is_dir() {
                walk(&p, root, out);
            } else if p.is_file() {
                let rel = p
                    .strip_prefix(root)
                    .unwrap_or(&p)
                    .to_string_lossy()
                    .replace('\\', "/");
                out.push((rel, p));
            }
        }
    }
    walk(&root, &root, &mut files);

    let mut out = String::from(
        "/// (path relative to assets/levels, contents) — generated by levels/build.rs.\n\
         #[allow(dead_code)]\n\
         pub static EMBEDDED_LEVELS: &[(&str, &str)] = &[\n",
    );
    for (rel, path) in &files {
        // include_str! rejects extended-length (\\?\) paths; keep the plain absolute form.
        let abs = path
            .canonicalize()
            .unwrap_or_else(|_| path.clone())
            .to_string_lossy()
            .trim_start_matches(r"\\?\")
            .to_string();
        let _ = writeln!(out, "    ({rel:?}, include_str!({abs:?})),");
    }
    out.push_str("];\n");
    std::fs::write(dest, out).expect("write embedded_levels.rs");
}
