//! The shipped **lineages** of the Evolved brain: frozen champions bred by
//! `cargo run -p ai --release --example evolve`. A mission pins a lineage by number
//! (`enemy = evolved 2`) and it never changes — re-running the tool writes new numbers.
//!
//! GENERATED by `crates/ai/examples/evolve.rs` — do not edit by hand.

use crate::evolved::{Genome, GENES};

/// `(generations bred, genome)` per lineage, oldest first.
pub const LINEAGES: &[(u32, [f32; GENES])] = &[
    (20, [0.0000, 0.1367, 0.3544, 0.7410, 0.8828, 1.0000, 0.7711, 1.0000, 0.0000, 0.3553, 0.6837, 0.0922, 0.7786, 0.2987, 0.4775]),
    (40, [0.0000, 0.1863, 0.3164, 0.7880, 0.8608, 1.0000, 0.7606, 0.8970, 0.0878, 0.3921, 0.2706, 0.0492, 0.8691, 0.3409, 0.7418]),
    (60, [0.0000, 0.1985, 0.5398, 0.7597, 0.8682, 0.7339, 0.7774, 0.7059, 0.2504, 0.5010, 0.1531, 0.0154, 0.7571, 0.3027, 0.8634]),
    (80, [0.0000, 0.1468, 0.4306, 0.8989, 0.5782, 0.6901, 0.7322, 0.5696, 0.2255, 0.5221, 0.1483, 0.0000, 0.6770, 0.2674, 0.7824]),
    (100, [0.0000, 0.1774, 0.0000, 1.0000, 0.6378, 0.7610, 0.7078, 0.5127, 0.1759, 0.5265, 0.1355, 0.1349, 0.9087, 0.3680, 0.7411]),
];

/// The genome of lineage `n`, if it exists.
pub fn genome(n: usize) -> Option<Genome> {
    LINEAGES.get(n).map(|&(_, g)| Genome(g))
}

/// The generation count lineage `n` was bred for, if it exists.
pub fn generation(n: usize) -> Option<u32> {
    LINEAGES.get(n).map(|&(g, _)| g)
}
