//! The shipped **lineages** of the Evolved brain: frozen champions bred by
//! `cargo run -p ai --release --example evolve`. A mission pins a lineage by number
//! (`enemy = evolved 2`) and it never changes — re-running the tool writes new numbers.
//!
//! GENERATED by `crates/ai/examples/evolve.rs` — do not edit by hand.

use crate::evolved::{Genome, GENES};

/// `(generations bred, genome)` per lineage, oldest first.
pub const LINEAGES: &[(u32, [f32; GENES])] = &[
    (20, [0.0000, 0.1367, 0.3544, 0.7410, 0.8828, 1.0000, 0.7711, 1.0000, 0.0000, 0.3553, 0.6837, 0.0922, 0.7786, 0.2987, 0.4775]),
    (40, [0.0000, 0.1863, 0.3164, 0.7880, 0.8608, 1.0000, 0.7606, 0.8970, 0.0878, 0.3921, 0.2706, 0.0492, 0.8691, 0.3409, 0.7418]),
];

/// The genome of lineage `n`, if it exists.
pub fn genome(n: usize) -> Option<Genome> {
    LINEAGES.get(n).map(|&(_, g)| Genome(g))
}

/// The generation count lineage `n` was bred for, if it exists.
pub fn generation(n: usize) -> Option<u32> {
    LINEAGES.get(n).map(|&(g, _)| g)
}
